server:
  port: 8002
spring:
  application:
    name: model
  redis:
    host: verloren.cn
    database: 3
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 600 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 300 #连接池中的最大空闲连接
        min-idle: 10 #连接池中的最小空闲连接
    password: h102
  thymeleaf:
    prefix: classpath:/template/
    check-template-location: true
    cache: false
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
#    jdbc-url: jdbc:mysql://127.0.0.1:3306/vt_model?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
#    username: root
#    password: ElfnfrV2rDYxgIxe
    jdbc-url: jdbc:mysql://127.0.0.1:3306/vt_model?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: 6ff65059f6464af0
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 500
      data-source-properties:
        setIdleTimeout: 60000
        setConnectionTimeout: 60000
        setValidationTimeout: 3000
        setLoginTimeout: 5
        setMaxLifetime: 60000
        maximumPoolSize: 20
        minimumIdle: 10
        connectionTimeout: 30000
        idleTimeout: 600000
        maxLifetime: 1800000
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        open-in-view: true
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect  #不加这句则默认为myisam引擎
  web:
    resources:
      static-locations: file:resources,classpath:/template/